# Generated by Django 5.2 on 2025-04-24 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_collection_owner_task_owner_alter_collection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.collection'),
        ),
    ]
